### ISSUE TITLE
Error in typings

### ISSUE THREAD

**Issue by ArgonAlex** [react-spring/react-use-gesture#158]
<img width="678" alt="Screen Shot 2020-04-10 at 8 48 12 PM" src="https://user-images.githubusercontent.com/4553695/79034700-2c1d7080-7b6d-11ea-8be2-6b4857f4bd2c.png">

react-use-gesture 7.0.12
typescript 3.8.3
@types/react 16.9.34
@types/react-dom 16.9.6

**Comment by dbismut** [comment]
Hey, I'm not getting that error, see below:
https://codesandbox.io/s/pedantic-water-5jlgv?file=/src/App.tsx

Is it possible that you set up a repo?

**Comment by ArgonAlex** [comment]
If I add `"allowSyntheticDefaultImports": true,` to your tsconfig.json and open up types.d.ts I see the error.

**Comment by ArgonAlex** [comment]
Checking out this repo and running type checking with `./node_modules/.bin/tsc --noEmit` also shows the error (among others because there are duplicate @types/react packages installed according to the yarn.lock file, but that's inconsequential).

**Comment by dbismut** [comment]
Right I see that now. I've published `7.0.13`, hope it fixes it.
Btw, I'm no typescript expert, so if you want to have a look at the project feel free!

**Comment by dbismut** [comment]
Btw, regarding the duplicate react packages being installed, I've tried to follow this [SO response](https://stackoverflow.com/questions/52399839/duplicate-identifier-librarymanagedattributes).

Looks like it worked, thanks for the help on all this!

**Comment by ArgonAlex** [comment]
Looks good. Thanks!

**Comment by Pipo93** [comment]
I'm still getting an error in `7.0.14` with `@types/react` version `16.9.34`:
```
Type '{ children: ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)>; ... 49 more ...; ref: (ref: HTMLDivElement | null) => void; }' is not assignable to type 'AnimatedProps<{ hidden?: boolean | undefined; style?: { alignContent?: string | undefined; alignItems?: string | undefined; alignSelf?: string | undefined; animationDelay?: string | undefined; ... 774 more ...; matrix3d?: readonly [...] | undefined; } | undefined; ... 253 more ...; ref?: ((instance: HTMLDivElement |...'.
  Types of property 'onMouseDown' are incompatible.
    Type '((event: MouseEvent<Element, MouseEvent>) => void) | undefined' is not assignable to type '((event: MouseEvent<HTMLDivElement, MouseEvent>) => void) | undefined'.
      Type '(event: MouseEvent<Element, MouseEvent>) => void' is not assignable to type '(event: MouseEvent<HTMLDivElement, MouseEvent>) => void'.
        Types of parameters 'event' and 'event' are incompatible.
          Type 'MouseEvent<HTMLDivElement, MouseEvent>' is missing the following properties from type 'MouseEvent<Element, MouseEvent>': detail, view
```

**Comment by eddydas** [comment]
I'm also hitting the same issue - what was your fix @Pipo93 ?

**Comment by stuffedmotion** [comment]
@eddydas @Pipo93 I have the exact same issue as well. Have you solved this?

**Comment by dbismut** [comment]
Can you please provide a sandbox or code excerpt? Also please trying using v10, see if it helps #300

**Comment by rrain0** [comment]
"@use-gesture/react": "^10.3.0",

Error while building docker image:

> [react build 7/7] RUN yarn run build:
0.789 yarn run v1.22.19
0.853 $ tsc && vite build
14.53 node_modules/@use-gesture/react/src/types.ts(4,31): error TS2536: Type 'Key' cannot be used to index type 'DOMAttributes<EventTarget>'.
14.61 error Command failed with exit code 2.
14.61 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn run build" did not complete successfully: exit code: 2
make: *** [Makefile:25: local.build-up] Error 17


SOLUTION:
I've found a way to solve it there: https://stackoverflow.com/a/41641001/14168271
Then i've implemented this to this problem and finally it works!
1) In poroject root create some folder to put your type overrides. I've created folder 'lib-types-overrides'.
2) In tsconfig.json add/update your "compilerOptions.path" to add this at begging of "path" object:
tsconfig.json: {
  "compilerOptions": {
     "paths": {
      "*": [
        "src/*",
        "lib-types-overrides/*"
      ],
      // other path aliases...
    }
  }
}
3) Create folders and files according to path: <project-root>/lib-types-overrides/@use-gesture/react/src/types.ts
4) Copy all content from <project-root>/node_modules/@use-gesture/react/src/types.ts to <project-root>/lib-types-overrides/@use-gesture/react/src/types.ts
Then in <project-root>/lib-types-overrides/@use-gesture/react/src/types.ts you can place // @ts-ignore :

import { DOMHandlers } from '@use-gesture/core/types'
export type ReactDOMAttributes = {
  // @ts-ignore
  [Key in keyof DOMHandlers]: React.DOMAttributes<EventTarget>[Key]
}
